# Generated by Django 5.1.7 on 2025-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('about', models.TextField(blank=True, null=True)),
                ('institution', models.TextField(blank=True, null=True)),
                ('degree', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Location', max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('experience_year', models.IntegerField(default=0, help_text='Years of experience in the field')),
                ('my_email', models.EmailField(max_length=254)),
                ('my_phone', models.CharField(max_length=15)),
                ('my_location', models.CharField(max_length=100)),
                ('my_github', models.URLField()),
                ('my_linkedin', models.URLField()),
                ('my_twitter', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='All_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=100)),
                ('skills_img', models.ImageField(upload_to='skills_images/')),
                ('proficiency', models.IntegerField(help_text='Proficiency level from 1 to 10')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='extra_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_link', models.URLField(blank=True, default='https://twitter.com/', null=True)),
                ('preview_link', models.URLField(blank=True, default='https://twitter.com/', null=True)),
                ('skills_used', models.ManyToManyField(blank=True, to='pages.all_skills')),
            ],
        ),
    ]
