# Generated by Django 5.1.7 on 2025-04-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='my_email',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='my_github',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='my_linkedin',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='my_location',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='my_phone',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='my_twitter',
        ),
    ]
