# Generated by Django 5.1.7 on 2025-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(help_text='Proficiency level from 1 to 10')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='preview_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Project Name', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='Project Type', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='projects', to='pages.all_skills'),
        ),
    ]
