# Generated by Django 5.1.7 on 2025-04-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_all_skills_delete_contact_delete_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_skills',
            name='skills_img',
            field=models.ImageField(default=1, upload_to='skills_images/'),
            preserve_default=False,
        ),
    ]
