# Generated by Django 5.1.7 on 2025-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_all_skills_skills_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='experience',
            new_name='about',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='experience_year',
            field=models.IntegerField(default=0, help_text='Years of experience in the field'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='more_skills',
            field=models.TextField(blank=True, help_text='Additional skills', null=True),
        ),
    ]
