# Generated by Django 5.1.7 on 2025-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_experience_rename_experience_aboutme_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Project Category', max_length=100),
        ),
    ]
