# Generated by Django 5.1.7 on 2025-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='more_skills',
            field=models.JSONField(blank=True, help_text='Additional skills in JSON format', null=True),
        ),
    ]
