# Generated by Django 5.1.7 on 2025-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_aboutme_more_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='more_skills',
            field=models.JSONField(default=list),
        ),
    ]
