# Generated by Django 5.1.7 on 2025-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_aboutme_more_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='education',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='more_skills',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='skills',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
