# Generated by Django 5.1.7 on 2025-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_extra_skills_rename_education_aboutme_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
